---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.imaginekube.com/aggregation-roles: '["role-template-manage-clusters","role-template-view-clusters","role-template-view-roles","role-template-view-workspaces","role-template-manage-workspaces","role-template-manage-users","role-template-view-users","role-template-manage-app-templates","role-template-view-app-templates","role-template-manage-platform-settings"]'
    imaginekube.com/creator: admin
  name: platform-admin
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'

---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRole
metadata:
  name: anonymous
rules: []

---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRoleBinding
metadata:
  name: anonymous
roleRef:
  apiGroup: iam.imaginekube.com/v1alpha2
  kind: GlobalRole
  name: anonymous
subjects:
  - apiGroup: iam.imaginekube.com/v1alpha2
    kind: Group
    name: system:unauthenticated

---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.imaginekube.com/role-template-rules: '{"basic": "view"}'
  labels:
    iam.imaginekube.com/role-template: "true"
  name: role-template-view-basic
rules: []

---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.imaginekube.com/module: Clusters Management
    iam.imaginekube.com/role-template-rules: '{"clusters": "view"}'
    imaginekube.com/alias-name: Clusters View
  labels:
    iam.imaginekube.com/role-template: "true"
  name: role-template-view-clusters
rules: []

---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.imaginekube.com/dependencies: '["role-template-view-clusters"]'
    iam.imaginekube.com/module: Clusters Management
    iam.imaginekube.com/role-template-rules: '{"clusters": "manage"}'
    imaginekube.com/alias-name: Clusters Management
  labels:
    iam.imaginekube.com/role-template: "true"
  name: role-template-manage-clusters
rules: []

---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.imaginekube.com/module: Access Control
    iam.imaginekube.com/role-template-rules: '{"workspaces": "view"}'
    imaginekube.com/alias-name: Workspaces View
  labels:
    iam.imaginekube.com/role-template: "true"
    kubefed.io/managed: "true"
  name: role-template-view-workspaces
rules: []

---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.imaginekube.com/dependencies: '["role-template-view-workspaces"]'
    iam.imaginekube.com/module: Access Control
    iam.imaginekube.com/role-template-rules: '{"workspaces": "manage"}'
    imaginekube.com/alias-name: Workspaces Management
  labels:
    iam.imaginekube.com/role-template: "true"
  name: role-template-manage-workspaces
rules: []


---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.imaginekube.com/module: Access Control
    iam.imaginekube.com/role-template-rules: '{"users": "view"}'
    imaginekube.com/alias-name: Users View
  labels:
    iam.imaginekube.com/role-template: "true"
  name: role-template-view-users
rules: []

---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.imaginekube.com/dependencies: '["role-template-view-users","role-template-view-roles"]'
    iam.imaginekube.com/module: Access Control
    iam.imaginekube.com/role-template-rules: '{"users": "manage"}'
    imaginekube.com/alias-name: Users Management
  labels:
    iam.imaginekube.com/role-template: "true"
  name: role-template-manage-users
rules: []

---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.imaginekube.com/dependencies: '["role-template-view-users"]'
    iam.imaginekube.com/module: Access Control
    iam.imaginekube.com/role-template-rules: '{"roles": "view"}'
    imaginekube.com/alias-name: Roles View
  labels:
    iam.imaginekube.com/role-template: "true"
  name: role-template-view-roles
rules: []

---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.imaginekube.com/dependencies: '["role-template-view-roles"]'
    iam.imaginekube.com/module: Access Control
    iam.imaginekube.com/role-template-rules: '{"roles": "manage"}'
    imaginekube.com/alias-name: Roles Management
  labels:
    iam.imaginekube.com/role-template: "true"
  name: role-template-manage-roles
rules: []

---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.imaginekube.com/module: Apps Management
    iam.imaginekube.com/role-template-rules: '{"app-templates": "view"}'
    imaginekube.com/alias-name: App Templates View
  labels:
    iam.imaginekube.com/role-template: "true"
  name: role-template-view-app-templates
rules: []

---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.imaginekube.com/dependencies: '["role-template-view-app-templates"]'
    iam.imaginekube.com/module: Apps Management
    iam.imaginekube.com/role-template-rules: '{"app-templates": "manage"}'
    imaginekube.com/alias-name: App Templates Management
  labels:
    iam.imaginekube.com/role-template: "true"
  name: role-template-manage-app-templates
rules: []

---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.imaginekube.com/module: Platform Settings
    iam.imaginekube.com/role-template-rules: '{"platform-settings": "manage"}'
    imaginekube.com/alias-name: Platform Settings Management
  labels:
    iam.imaginekube.com/role-template: "true"
  name: role-template-manage-platform-settings
rules: []

---
apiVersion: iam.imaginekube.com/v1alpha2
kind: GlobalRoleBinding
metadata:
  name: admin
roleRef:
  apiGroup: iam.imaginekube.com/v1alpha2
  kind: GlobalRole
  name: platform-admin
subjects:
  - apiGroup: iam.imaginekube.com/v1alpha2
    kind: User
    name: admin

---
apiVersion: tenant.imaginekube.com/v1alpha2
kind: WorkspaceTemplate
metadata:
  labels:
    kubefed.io/managed: "false"
  annotations:
    imaginekube.com/creator: admin
    imaginekube.com/description: "system-workspace is a built-in workspace automatically created by ImagineKube. It contains all system components to run ImagineKube."
  name: system-workspace
spec:
  placement:
    clusterSelector: {}
  template:
    spec:
      manager: admin
      networkIsolation: false

---
apiVersion: tenant.imaginekube.com/v1alpha1
kind: Workspace
metadata:
  labels:
    kubefed.io/managed: "false"
  annotations:
    imaginekube.com/creator: admin
  name: system-workspace
spec:
  manager: admin
  networkIsolation: false